apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dotnetcore
  description: backstage.io
  annotations:
    github.com/project-slug: 'NisargShah1410/dotnetcore'
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: user:guest
