name: DOTNET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.1.20452.10
    - name: where are we
      run: pwd
    - name: Install dependencies
      run: dotnet restore ./SampleCoreApp/
    - name: Build
      run: dotnet build --configuration Release --no-restore ./SampleCoreApp
    - name: Test
      run: |
        dotnet test --no-restore --verbosity normal ./SampleCoreApp
        
    - name: dotnet publish
      run: |
        dotnet add package coverlet
        dotnet publish -c Release -o dotnetcorewebapp --collect:"XPlat Code Coverage" ./SampleCoreApp 
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: sampledotnetcoredemo
        publish-profile: ${{ secrets.DOTNET_WEB_APP }}
        package: './dotnetcorewebapp'
